Update coverity-analysis.yml

diff --git a/.github/workflows/coverity-analysis.yml b/.github/workflows/coverity-analysis.yml
--- a/.github/workflows/coverity-analysis.yml
+++ b/.github/workflows/coverity-analysis.yml
@@ -52,8 +52,8 @@ jobs:
         run: |
           chmod +x scripts/build.alpine.release.sh
           chmod +x ./cov-analysis-linux64-2024.6.1/bin/cov-build
-          ls -la ./cov-analysis-linux64-2024.6.1/bin/cov-build
-          ./cov-analysis-linux64-2024.6.1/bin/cov-build --dir cov-int bash scripts/build.alpine.release.sh || echo 'Errors during build with Coverity'
+          ls -la scripts
+          ./cov-analysis-linux64-2024.6.1/bin/cov-build --dir cov-int bash ./scripts/build.alpine.release.sh || echo 'Errors during build with Coverity'
       - name: Compress with bzip2
         shell: sh
         run: |
