Update coverity-analysis.yml

diff --git a/.github/workflows/coverity-analysis.yml b/.github/workflows/coverity-analysis.yml
--- a/.github/workflows/coverity-analysis.yml
+++ b/.github/workflows/coverity-analysis.yml
@@ -41,7 +41,7 @@ jobs:
         shell: bash
         run: |
           choco install pkgconfiglite curl
-          cov-analysis-win64-2024.6.1/bin/cov-build.exe --dir cov-int bash scripts/build.windows.release.sh || echo 'Errors when building using Coverity'
+          cov-analysis-win64-2024.6.1/bin/cov-build.exe --dir cov-int bash -c "scripts/build.windows.release.sh || echo 'Errors when building using Coverity'"
       - name: Compress with bzip2
         shell: powershell
         run: |
