Update coverity-analysis.yml

diff --git a/.github/workflows/coverity-analysis.yml b/.github/workflows/coverity-analysis.yml
--- a/.github/workflows/coverity-analysis.yml
+++ b/.github/workflows/coverity-analysis.yml
@@ -32,7 +32,7 @@ jobs:
       - name: Installing dependencies
         shell: sh
         run: |
-          apk add bash git nodejs npm
+          apk add bash git nodejs npm gcompat
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
@@ -51,9 +51,7 @@ jobs:
         shell: sh
         run: |
           chmod +x scripts/build.alpine.release.sh
-          chmod +x ./cov-analysis-linux64-2024.6.1/bin/cov-build
-          ls -la scripts
-          bash ./cov-analysis-linux64-2024.6.1/bin/cov-build --dir cov-int ./scripts/build.alpine.release.sh || echo 'Errors during build with Coverity'
+          ./cov-analysis-linux64-2024.6.1/bin/cov-build --dir cov-int ./scripts/build.alpine.release.sh || echo 'Errors during build with Coverity'
       - name: Compress with bzip2
         shell: sh
         run: |
